name: Deploy to VPS
on:
  workflow_run:
    workflows: ["Build & Push Docker Images"]
    types: [ completed ]
    branches: [ main ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Pull & restart (SSH)
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.PROD_HOST }}
        key:  ${{ secrets.PROD_KEY }}
        script: |
          cd /srv/nso
          docker compose pull
          docker compose up -d --remove-orphans
          docker image prune -f
